### ISSUE TITLE
Flagermus virker ikke på LuaKit

### ISSUE THREAD

**Issue by asger-weirsoee** [f-klubben/stregsystemet#220]
The question about the best browser is trivial to answer, as we all know and love the Luakit browser.
It seems like the spooktober-bats however is not implemented correctly on the Stregsystem, as they don't show after a set amount of time.

Now, as the only _real_ browser is the Luakit, I find it hard to understand why this has not been addressed before. But I promptly request that this, serious flaw, is regarded with the respect that it deserves.

See attached image for clarification!
![image](https://user-images.githubusercontent.com/15718221/96442415-61390880-120b-11eb-9ab0-3d6dda2b984b.png)

**Comment by cogitantium** [comment]
:bat: :bat: :bat:

**Comment by atjn** [comment]
We made some recent changes and I am proud to announce it works now:
![image](https://github.com/user-attachments/assets/e241c774-ee6e-4142-a0ea-b5de4e93e4f9)

The white box around the bats is because luakit does not support opacity in webm videos. This is obviously a skill issue for luakit, which only luakit can solve.
