### ISSUE TITLE
Make github activity heatmap-like statistics for purchases

### ISSUE THREAD

**Issue by falkecarlsen** [f-klubben/stregsystemet#328]
I like comparing e-penises, therefore we should have a stat on the userinfo page showing a heatmap of purchases distinguished by colour on category perhaps. 

I'm sure a generic lookalike exists.

**Comment by krestenlaust** [comment]
>  distinguished by colour on category perhaps.

The github heatmap doesn't support multiple colors, as I see it. What kinds of categories are you thinking of?

![Screenshot of github heatmap](https://github.com/f-klubben/stregsystemet/assets/17174333/d6caa184-a104-4e75-ba7e-65f7929e4315)

**Comment by krestenlaust** [comment]
This is what I have so far
![](https://github.com/f-klubben/stregsystemet/assets/17174333/4d6eff64-ebd7-458c-9647-a67e99be6675)

**Comment by falkecarlsen** [comment]
> colours and categories
I was thinking that each major category is assigned a base color beer=red, energy=green, soda=blue. Then the color of a day would be the proportional mixing of these colours. The brightness of a day could be the proportion of money spent in relation to the day where you spent the most money.

@krestenlaust Nice WIP! Consider replicating that Sunday goes on top as github does, I like the effect that the weekend pads top and bottom of the work-week in the heatmap.

**Comment by krestenlaust** [comment]
I've finished proportional mixing. The issue I'm facing is its crude appearance. I decided to do brightness based on the day with most items bought, as opposed to money spent, because the colors are mixed proportionally based on items as well.
![Screenshot of heatmap](https://github.com/f-klubben/stregsystemet/assets/17174333/f9a06b11-5d53-4be7-a567-02e8108e9697)
The link at the button of the figure, is clickable and changes table mode to display general item data bought without taking categories into account.
![Screenshot of general view in heatmap](https://github.com/f-klubben/stregsystemet/assets/17174333/4533e147-bbce-48a3-b768-392250c50db5)


I want for the user to be able to view what items where bought on each day. I'm considering either making a popup (doesn't fit in with Stregsystem look), or temporarily adding a count/number next to each item when hovering over a day. Though I'm not sure how much I can rely on client computations given the, supposedly, weak CPU of the live system. (It would require more javascript).
