### ISSUE TITLE
Buy butten greyed out when navigating back from usermenu

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#356]
When using browser (Firefox 117) back-button, the purchase button is greyed out. It's most likely something to do with caching and forms-submitting not cooperating properly.

Greyed out button:
![Screenshot of purchase button being greyed out](https://github.com/f-klubben/stregsystemet/assets/17174333/310bf9b8-034f-4037-8869-c3aef97f5242)

**Comment by JakobTopholt** [comment]
I can confirm that this is also the case in Chrome Version 121.0.6167.185 (26. February 2024)

**Comment by BoAnd** [comment]
The problem is in this line. We disable the button and ever reset it when coming back. 
https://github.com/f-klubben/stregsystemet/blob/3bc41ba03e4b0b206d1af6286f88fb9356021828/stregsystem/templates/stregsystem/index.html#L31

We can solve this 2 ways:
1. Delete the onsubmit attr
2. Add this to the body 
```
<script>
  window.addEventListener("pageshow", (event) => {
    document.getElementById('buybutton').disabled = false;
  });
</script>
```

**Comment by krestenlaust** [comment]
Do you have a preference?

I don't think there's any danger to not disabling the purchase button, but I do think it's slightly better UX to indicate that something is happening.

I'll just quickly spin-up a draft using the second solution
