### ISSUE TITLE
The Kiosk screen are currently served by an external server

### ISSUE THREAD

**Issue by VirtualSatai** [f-klubben/stregsystemet#45]
At the moment each of the 3 raspberry pi + big screens are served by Jacob Elefsens home page. This is not ideal as he's the only one with access to administrating it. 

We have already asked about it, and he agrees. 

We are considering making it a part of the admin panel of the stregsystem, and limiting the access to a few people, chosen by Forstyrrelsen.

**Comment by DelusionalLogic** [comment]
I think the feature as implemented in #46 is a fantastic addition to the arsenal of advertising opportunities forstyrrelsen has.

I envision moving a lot of the needs currently filled by mails (such as advertising events) could be replaced, or at least greatly supplemented, by these billboard screens.

We'd love input on how this feature can be improved in the future.

**Comment by jacobelefsen** [comment]
Only two of the raspberry pi is served by my domain.  All relevant people has access, both from the fklub and external partners. I move the current solution to the fklub server when I have time.

**Comment by DelusionalLogic** [comment]
#46 is a clean reimplementation of what we believe the php script serving the images is doing.

The reasons for reimplementing it are twofold. First we remove any chance of licensing issues. Secondly, and more importantly, we integrate it into an existing system, which should make maintenance easier in the future (since it wont just be a bunch of disconnected scripts). It might also be possible to do different advertisement based upon other events in the system (such as scheduling advertisements for specific periods, or maybe advertising for foobar every Friday) in the future.

Is it a hard requirement that external partners are able to upload directly? I'd imagine they'd rather drop an email to someone and have us do it for them, but I haven't discussed it with them. if it is a requirement we need to get that into #46.

**Comment by jones-g** [comment]
I think moving this to an app alongside stregsystemet in the django project is a great idea. It is possible but not required that we can integrate with things in the stregsystem like showing the price of certain products live and that sort of deal. 

Regarding external access we already have a solution for this imo. Users of the stregsystemet are disjointed from members. Thus we can just create a user for the external partners that have access to upload on some view we create and Bob's your uncle!

**Comment by jacobelefsen** [comment]
Perhaps you should ask for the requirements to the solution before developing anything.

**Comment by jones-g** [comment]
Well then what are the requirements?

I highly doubt that something has been implemented that cannot be replicated in django by one of the crafty volunteers on this project.

**Comment by VirtualSatai** [comment]
@jacobelefsen Any updates on the requirements?
